config/routes.rb
Rails.application.routes.draw do
  get '/snapshot' => 'snapshot#index'
  get 'profiles/show'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
 

  resources :users
  resources :username
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :views
  resources :relationships

  root 'static_pages#home'

  get '/contact' => 'static_pages#contact'
  get '/help' => 'static_pages#help'
  get '/terms' => 'static_pages#terms'
  get '/:id' => 'profiles#show'

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	layout "home"

	def terms
	end

	def contact
	end

	def help
	end

	def home
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<h1>Call me.</h1>

app/views/static_pages/help.html.erb
<h1>Help</h1>

app/views/static_pages/home.html.erb
	<div class="home-search">
			<div class="home-search-screen">
				<div class="home-logo-main">
					<%= image_tag('home/home-logo-main.png') %>
				</div>

					<div class="home-search-form">
						<div class="home-control-group">
							<%= form_tag users_path, :method => :get do %>
							    <%= text_field_tag :search, params[:search], class: "home-search-field" %>
							    <%= submit_tag "Search", :name => nil, class: "home-btn " %>
							<% end %>
						</div>
					</div>
			</div>
	</div>

<footer>
	<ul>
		<li class="footer-links"><%= link_to 'Contact Us', contact_path %></li>
		<li class="footer-links"><%= link_to 'Help', help_path %></li>
		<li class="footer-links"><%= link_to 'Terms of Service', terms_path, target: "_blank" %></li>
		<li>Copyright &#0169; 2014</li>		
	</ul>
</footer>

app/views/static_pages/terms.html.erb
<h1>Terms</h1>