config/routes.rb
Rails.application.routes.draw do
  get '/snapshot' => 'snapshot#index'
  get 'profiles/show'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
 

  resources :users
  resources :username
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :views
  resources :relationships

  root 'static_pages#home'

  get '/contact' => 'static_pages#contact'
  get '/help' => 'static_pages#help'
  get '/terms' => 'static_pages#terms'
  get '/:id' => 'profiles#show'

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	has_many :views, dependent: :destroy
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

	validates :email, presence: true,
					  uniqueness: true,
					  format: {
					  	with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.|[A-Za-z]+\z/
					  }

	validates :username, presence: true,
  					  uniqueness: true

	validates :terms_of_service, acceptance: true
  


	before_save :downcase_email

	def feed 
	end

	def following?(other_user)
		relationships.find_by(followed_id: other_user.id)
	end

	def follow!(other_user)
		relationships.create!(followed_id: other_user.id)
	end

	def unfollow!(other_user)
    	relationships.find_by(followed_id: other_user.id).destroy
  	end

	def downcase_email
		self.email = email.downcase
	end

	def generate_password_reset_token!
    update_attribute(:password_reset_token, SecureRandom.urlsafe_base64(48))
  end

  searchable do
    text :full_name, boost: 5.0
    text :username, boost: 4.0
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers]
  before_action :admin_user, only: :destroy

  def index
    @query = User.search do
        fulltext params[:search]
    end
    @users = @query.results
  end

  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to views_path, success: 'Thanks for signing up!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    
    @user = User.find(params[:id])

if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
    end
  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted"
    redirect_to daily_path
    end

     def following
    @title = "Following"
    @users = User.find(params[:id])
    @users = User.all
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = User.find(params[:id])
    @users = User.all
    render 'show_follow'
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :password, :username, :terms_of_service)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="login">
    <div class="login-screen">
      <div class="app-title">
        <h1>Register</h1>
      </div>

                 <div class="login-form">
                  
                  <div class="control-group">
                    <%= f.label :full_name, "Full Name", class: "full-name-field" %><br>
                    <%= f.text_field :full_name %>
                  </div>
                  
                  <div class="control-group">
                    <%= f.label :email, "Email" %><br>
                    <%= f.text_field :email %>
                  </div>
                  
                  <div class="control-group">
                    <%= f.label :password, "Password" %><br>
                    <%= f.password_field :password %>
                  </div>
                  
                  <div class="control-group">
                    <%= f.label :username, "Username" %><br>
                    <%= f.text_field :username %>
                  </div>

                  <div class="checkbox">
                  <%= check_box_tag :remember_me, class: "checkbox-field" %>
                  <%= label_tag :remember_me, "Keep me signed in?", class: "checkbox-tag" %>  
                  </div>
                  
                  <div class="checkbox">
                  <%= f.check_box :terms_of_service, class: "checkbox-field" %>
                  <%= f.label :terms_of_service, "I agree to the #{link_to 'Terms of Service', terms_path, target: "_blank"}.".html_safe, class: "checkbox-tag" %>
                  </div>
                  
                    <%= f.submit "Join!", class: "btn btn-primary btn-large btn-block" %>
                  
                  </div>
    </div>
  </div>

<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to current_user.full_name, current_user.username  %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

    <%= form_for(@user) do |f| %>

      <%= f.label :full_name %>
      <%= f.text_field :full_name %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>


      <%= f.submit "Save changes" %>
    <% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      
      <%= link_to user.full_name, user.username %>
      <%= link_to "@" + user.username, user.username %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', snapshot_path  %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>


      <h1><%= @user.full_name %></h1>
      <span><%= link_to "view my profile", current_user.username %></span>
      

 <% @users.each do |user| %>
 
 <% end %>