config/routes.rb
Rails.application.routes.draw do
  get '/snapshot' => 'snapshot#index'
  get 'profiles/show'

  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout
 

  resources :users
  resources :username
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :views
  resources :relationships

  root 'static_pages#home'

  get '/contact' => 'static_pages#contact'
  get '/help' => 'static_pages#help'
  get '/terms' => 'static_pages#terms'
  get '/:id' => 'profiles#show'

  resources :users do
    member do
      get :following, :followers
    end
  end

end

app/views/views/_form.html.erb
<%= form_for(@view) do |f| %>
  <% if @view.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@view.errors.count, "error") %> prohibited this view from being saved:</h2>

      <ul>
      <% @view.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/views/_views.html.erb
<% provide(:title, @user.full_name) %>
<div class="row">
  
  <aside>
    
  </aside>
  <div>
  	<a href="<%= views_path %>">
    <% if @user.views.any? %>
      <h3>Views (<%= @user.views.count %>)</h3>
       

    <% end %>
</a>
  </div>
</div>

app/views/views/edit.html.erb
<h1>Editing view</h1>

<%= render 'form' %>

<%= link_to 'Show', @view %> |
<%= link_to 'Back', views_path %>

app/views/views/index.html.erb
<h1>Listing views</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @views.each do |view| %>
      <tr>
        <td><%= view.name %></td>
        <td><%= view.content %></td>
        <td><%= link_to 'Show', view %></td>
        <td><%= link_to 'Edit', edit_view_path(view) %></td>
        <td><%= link_to 'Destroy', view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New View', new_view_path %>

app/views/views/new.html.erb
<h1>New view</h1>

<%= render 'form' %>

<%= link_to 'Back', views_path %>

app/views/views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @view.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @view.content %>
</p>

<%= link_to 'Edit', edit_view_path(@view) %> |
<%= link_to 'Back', views_path %>